//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotCheckAdminPortal {
	
	
	public partial class index {
		
		protected System.Web.UI.HtmlControls.HtmlForm indexForm;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyUsername;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyPassword;
		
		protected System.Web.UI.WebControls.Button LoginButton;
		
		protected System.Web.UI.WebControls.Label ErrorLabel;
		
		protected System.Web.UI.WebControls.Button SignUpInsteadButton;
	}
}
