//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotCheckAdminPortal {
	
	
	public partial class Signup {
		
		protected System.Web.UI.HtmlControls.HtmlForm SignupForm;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyUsername;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyName;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyStreet;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyCity;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyZipCode;
		
		protected System.Web.UI.WebControls.DropDownList DropDownState;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyPassword1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCompanyPassword2;
		
		protected System.Web.UI.WebControls.Button SignUpButton;
		
		protected System.Web.UI.WebControls.Label ErrorLabel;
		
		protected System.Web.UI.WebControls.Button LoginInsteadButton;
	}
}
