//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotCheckAdminPortal
{


   public partial class ViewCameras
   {

      /// <summary>
      /// viewCamerasBody control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl viewCamerasBody;

      /// <summary>
      /// cameraForm control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlForm cameraForm;

      /// <summary>
      /// loadingCamerasDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl loadingCamerasDiv;

      /// <summary>
      /// deployedCameraUpdateProgress control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdateProgress deployedCameraUpdateProgress;

      /// <summary>
      /// undeployedCameraUpdateProgress control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdateProgress undeployedCameraUpdateProgress;

      /// <summary>
      /// CompanyNameLiteral control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Literal CompanyNameLiteral;

      /// <summary>
      /// camerasBodyDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl camerasBodyDiv;

      /// <summary>
      /// cameraScriptManager control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.ScriptManager cameraScriptManager;

      /// <summary>
      /// alertUpdatePanel control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdatePanel alertUpdatePanel;

      /// <summary>
      /// alertDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertDiv;

      /// <summary>
      /// LeftRightContainer control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl LeftRightContainer;

      /// <summary>
      /// modalUpdatePanel control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdatePanel modalUpdatePanel;

      /// <summary>
      /// modalDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl modalDiv;

      /// <summary>
      /// deployCameraContainerDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl deployCameraContainerDiv;

      /// <summary>
      /// deployedCameraUpdatePanel control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdatePanel deployedCameraUpdatePanel;

      /// <summary>
      /// left control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl left;

      /// <summary>
      /// comboBoxDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl comboBoxDiv;

      /// <summary>
      /// deployedCameraContainer control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl deployedCameraContainer;

      /// <summary>
      /// undeployedCameraUpdatePanel control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdatePanel undeployedCameraUpdatePanel;

      /// <summary>
      /// right control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl right;

      /// <summary>
      /// undeployedCameraDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl undeployedCameraDiv;

      /// <summary>
      /// undeployedCameraContainer control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl undeployedCameraContainer;

      /// <summary>
      /// deployModalUpdatePanel control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdatePanel deployModalUpdatePanel;

      /// <summary>
      /// parkingLotDropDownDeployList control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl parkingLotDropDownDeployList;
   }
}
