//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI;

namespace SpotCheckAdminPortal {	
	
	public partial class ViewParkingLots {

		protected System.Web.UI.HtmlControls.HtmlGenericControl loadingParkingLotDiv;

		protected UpdateProgress parkingLotUpdateProgress;

		protected ScriptManager parkingLotScriptManager;

		protected UpdatePanel parkingLotUpdatePanel;

		protected System.Web.UI.HtmlControls.HtmlGenericControl viewParkingLotBody;

		protected System.Web.UI.HtmlControls.HtmlForm parkingLotForm;
		
		protected System.Web.UI.WebControls.Literal CompanyNameLiteral;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl parkingLotContainer;

		protected System.Web.UI.HtmlControls.HtmlGenericControl alertDiv;
	}
}
