//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotCheckAdminPortal
{


   public partial class ViewCameras
   {

      /// <summary>
      /// viewCamerasBody control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl viewCamerasBody;

      /// <summary>
      /// cameraForm control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlForm cameraForm;

      /// <summary>
      /// loadingCamerasDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl loadingCamerasDiv;

      /// <summary>
      /// cameraUpdateProgress control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdateProgress cameraUpdateProgress;

      /// <summary>
      /// CompanyNameLiteral control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Literal CompanyNameLiteral;

      /// <summary>
      /// camerasBodyDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl camerasBodyDiv;

      /// <summary>
      /// cameraScriptManager control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.ScriptManager cameraScriptManager;

      /// <summary>
      /// cameraUpdatePanel control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdatePanel cameraUpdatePanel;

      /// <summary>
      /// alertDiv control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl alertDiv;

      /// <summary>
      /// cameraContainer control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl cameraContainer;
   }
}
