//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotCheckAdminPortal {
	
	
	public partial class ViewParkingLots {
		
		protected System.Web.UI.HtmlControls.HtmlForm dashboardForm;
		
		protected System.Web.UI.WebControls.Literal CompanyNameLiteral;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl parkingLotContainer;
	}
}
