//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotCheckAdminPortal {
	
	
	public partial class ViewCameras {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl viewCamerasBody;
		
		protected System.Web.UI.HtmlControls.HtmlForm cameraForm;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl loadingCamerasDiv;
		
		protected System.Web.UI.UpdateProgress deployedCameraUpdateProgress;
		
		protected System.Web.UI.UpdateProgress undeployedCameraUpdateProgress;
		
		protected System.Web.UI.WebControls.Literal CompanyNameLiteral;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl camerasBodyDiv;
		
		protected System.Web.UI.ScriptManager cameraScriptManager;
		
		protected System.Web.UI.UpdatePanel alertUpdatePanel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl alertDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl LeftRightContainer;
		
		protected System.Web.UI.UpdatePanel modalUpdatePanel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl modalDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl deployCameraContainerDiv;
		
		protected System.Web.UI.UpdatePanel deployedCameraUpdatePanel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl left;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl comboBoxDiv;
		
		protected System.Web.UI.WebControls.DropDownList parkingLotDropDownList;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl deployedCameraContainer;
		
		protected System.Web.UI.UpdatePanel undeployedCameraUpdatePanel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl right;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl undeployedCameraDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl undeployedCameraContainer;
		
		protected System.Web.UI.UpdatePanel deployModalUpdatePanel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl parkingLotDropDownDeployList;
       
	}
}
